# Generated by Django 5.2.8 on 2025-12-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_loginrecord_onlineuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='vipapplication',
            name='reject_reason',
            field=models.TextField(blank=True, null=True, verbose_name='拒绝原因'),
        ),
    ]
