# Generated by Django 4.2.7 on 2025-12-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='local_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='本地存储路径'),
        ),
        migrations.AlterField(
            model_name='file',
            name='swift_container',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Swift容器'),
        ),
        migrations.AlterField(
            model_name='file',
            name='swift_object',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Swift对象名'),
        ),
    ]
